[package]
name = "test_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = "0.8.8"
chrono = "0.4.43"
colored = "3.1.1"
dirs = "6.0.0"
git2 = "0.20.4"
serde = {version = "1.0.228", features = ["derive"]}
tokio = { version = "1.49.0", features = ["full"] }
